[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
actor-derive = { workspace = true }

candid = { workspace = true }
derive_deref = { workspace = true }
serde = { workspace = true }
icrc-ledger-types = { workspace = true }
anyhow = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
