[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
apresh-derive = { workspace = true }

candid = { workspace = true }
derive_deref = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
types = { workspace = true }
ic-stable-structures = { workspace = true }
store = { workspace = true }
apresh-crypto = { workspace = true }

[features]
# icp = ["dep:ic-stable-structures"]
icp = ["types/icp"]
default = []
