[workspace]
members = ["src/contract", "src/crates/actor-derive", "src/crates/engine"]
resolver = "2"


[workspace.dependencies]
actor-derive = { path = "src/crates/actor-derive" }
engine = { path = "src/crates/engine" }

candid = "0.10.12"
derive_deref = "1.1.1"
ic-cdk = "0.17.1"
ic-cdk-timers = "0.11.0"                                                      # Feel free to remove this dependency if you don't need timers
serde = { version = "1.0.217", features = ["derive"] }
icrc-ledger-types = "0.1.6"
anyhow = "1.0.95"
image = { version = "0.24", features = ["png"], default-features = false }
thiserror = "2.0.11"
qrcode-generator = "4.1"
colorgrad = "0.6"
sha2 = "0.10.8"
hex-literal = "0.4.1"
hex = "0.4.3"
