[package]
name = "contract"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = { workspace = true }
ic-cdk = { workspace = true }
ic-cdk-timers = { workspace = true }
derive_deref = { workspace = true }
serde = { workspace = true }
icrc-ledger-types = { workspace = true }
anyhow = { workspace = true }
image = { workspace = true }
qrcode-generator = { workspace = true }
colorgrad = { workspace = true }
sha2 = { workspace = true }
hex-literal = { workspace = true }
hex = { workspace = true }

actor-derive = { workspace = true }
engine = { workspace = true }
apresh-qr = { workspace = true }

[dev-dependencies]
pocket-ic = "6.0.0"
rstest = "0.24.0"
