[package]
name = "entrypoint"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full", "parsing"] }
quote = "1.0"
proc-macro2 = "1.0"
apresh-store = { workspace = true }
apresh-derive = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
trybuild = "1.0"
candid = { workspace = true }