[package]
name = "state"
version = "0.1.0"
edition = "2021"

[dependencies]
ic-stable-structures = { workspace = true }
candid = { workspace = true }
engine = { workspace = true, features = ["icp"] }
serde = { workspace = true }
bcs = { workspace = true }

[dev-dependencies]
apresh-derive = { workspace = true }
