[package]
name = "apresh-qr"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
candid = { workspace = true }
colorgrad = { workspace = true }
image = { workspace = true }
serde = { workspace = true }
qrcode-generator = { workspace = true }

engine = { workspace = true }
