name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build Contract Binary
        run: rustup target add wasm32-unknown-unknown && cargo build --target wasm32-unknown-unknown -r -p contract
      - name: Test
        run: cargo nextest run --all --all-targets
      - name: Clippy
        run: cargo clippy --all --all-targets -- -D warnings
